export const TOOLS = [
  // PDF Tools
  { id: 'pdf-merge',            name: 'Merge PDF',           description: 'Combine multiple PDF files into one',              icon: '🔗',  category: 'pdf',     path: '/tools/merge-pdf',            color: 'from-red-500/20 to-orange-500/20',    accent: 'text-red-400',     border: 'hover:border-red-500/50',     popular: true },
  { id: 'pdf-split',            name: 'Split PDF',           description: 'Extract specific pages from any PDF',              icon: '✂️',  category: 'pdf',     path: '/tools/split-pdf',            color: 'from-orange-500/20 to-yellow-500/20', accent: 'text-orange-400',  border: 'hover:border-orange-500/50' },
  { id: 'pdf-compress',         name: 'Compress PDF',        description: 'Reduce PDF file size while keeping quality',       icon: '🗜️',  category: 'pdf',     path: '/tools/compress-pdf',         color: 'from-yellow-500/20 to-amber-500/20',  accent: 'text-yellow-400',  border: 'hover:border-yellow-500/50',  popular: true },
  { id: 'pdf-to-word',          name: 'PDF to Word',         description: 'Convert PDF to editable Word files',               icon: '📝',  category: 'pdf',     path: '/tools/pdf-to-word',          color: 'from-blue-500/20 to-indigo-500/20',   accent: 'text-blue-400',    border: 'hover:border-blue-500/50',    popular: true },
  { id: 'jpg-to-pdf',           name: 'JPG to PDF',          description: 'Convert images into a PDF document',               icon: '🖼️',  category: 'pdf',     path: '/tools/jpg-to-pdf',           color: 'from-purple-500/20 to-pink-500/20',   accent: 'text-purple-400',  border: 'hover:border-purple-500/50' },
  { id: 'pdf-to-jpg',           name: 'PDF to JPG',          description: 'Convert each PDF page to JPG image',               icon: '🖼️',  category: 'pdf',     path: '/tools/pdf-to-jpg',           color: 'from-pink-500/20 to-rose-500/20',     accent: 'text-pink-400',    border: 'hover:border-pink-500/50',    isNew: true },
  { id: 'word-to-pdf',          name: 'Word to PDF',         description: 'Convert Word .docx files to PDF format',           icon: '📄',  category: 'pdf',     path: '/tools/word-to-pdf',          color: 'from-sky-500/20 to-blue-500/20',      accent: 'text-sky-400',     border: 'hover:border-sky-500/50',     isNew: true },
  { id: 'pdf-watermark',        name: 'PDF Watermark',       description: 'Add custom watermark to every PDF page',           icon: '💧',  category: 'pdf',     path: '/tools/pdf-watermark',        color: 'from-cyan-500/20 to-blue-500/20',     accent: 'text-cyan-400',    border: 'hover:border-cyan-500/50',    popular: true },
  { id: 'pdf-remove-watermark', name: 'Remove Watermark',    description: 'Remove watermarks from PDF files',                 icon: '🧹',  category: 'pdf',     path: '/tools/pdf-remove-watermark', color: 'from-lime-500/20 to-green-500/20',    accent: 'text-lime-400',    border: 'hover:border-lime-500/50' },
  { id: 'pdf-protect',          name: 'Protect PDF',         description: 'Add password protection to PDF files',             icon: '🔐',  category: 'pdf',     path: '/tools/pdf-protect',          color: 'from-green-500/20 to-emerald-500/20', accent: 'text-green-400',   border: 'hover:border-green-500/50' },
  { id: 'pdf-unlock',           name: 'Unlock PDF',          description: 'Remove password protection from PDF',              icon: '🔓',  category: 'pdf',     path: '/tools/pdf-unlock',           color: 'from-amber-500/20 to-orange-500/20',  accent: 'text-amber-400',   border: 'hover:border-amber-500/50' },
  { id: 'pdf-page-numbers',     name: 'Add Page Numbers',    description: 'Add page numbers to every PDF page',               icon: '🔢',  category: 'pdf',     path: '/tools/pdf-page-numbers',     color: 'from-violet-500/20 to-purple-500/20', accent: 'text-violet-400',  border: 'hover:border-violet-500/50' },
  { id: 'pdf-to-text',          name: 'PDF to Text',         description: 'Extract all text from PDF files instantly',        icon: '📄',  category: 'pdf',     path: '/tools/pdf-to-text',          color: 'from-teal-500/20 to-cyan-500/20',     accent: 'text-teal-400',    border: 'hover:border-teal-500/50' },
  { id: 'repair-pdf',           name: 'Repair PDF',          description: 'Fix corrupted or damaged PDF files',               icon: '🔧',  category: 'pdf',     path: '/tools/repair-pdf',           color: 'from-orange-500/20 to-red-500/20',    accent: 'text-orange-400',  border: 'hover:border-orange-500/50',  isNew: true },
  { id: 'remove-pdf-pages',     name: 'Remove PDF Pages',    description: 'Delete specific pages from any PDF',               icon: '🗑️',  category: 'pdf',     path: '/tools/remove-pdf-pages',     color: 'from-red-500/20 to-rose-500/20',      accent: 'text-red-400',     border: 'hover:border-red-500/50',     isNew: true },
  // Image Tools
  { id: 'img-compress',         name: 'Compress Image',      description: 'Reduce image size without losing quality',         icon: '📸',  category: 'image',   path: '/tools/compress-image',       color: 'from-green-500/20 to-emerald-500/20', accent: 'text-green-400',   border: 'hover:border-green-500/50',   popular: true },
  { id: 'img-resize',           name: 'Resize Image',        description: 'Resize images to any custom dimension',            icon: '📐',  category: 'image',   path: '/tools/resize-image',         color: 'from-teal-500/20 to-cyan-500/20',     accent: 'text-teal-400',    border: 'hover:border-teal-500/50' },
  { id: 'img-convert',          name: 'Convert Image',       description: 'Convert between JPG, PNG, WEBP formats',           icon: '🔄',  category: 'image',   path: '/tools/convert-image',        color: 'from-cyan-500/20 to-sky-500/20',      accent: 'text-cyan-400',    border: 'hover:border-cyan-500/50' },
  { id: 'image-to-text',        name: 'Image to Text (OCR)', description: 'Extract text from images and screenshots',         icon: '🔤',  category: 'image',   path: '/tools/image-to-text',        color: 'from-rose-500/20 to-pink-500/20',     accent: 'text-rose-400',    border: 'hover:border-rose-500/50',    popular: true },
  { id: 'background-remover',   name: 'Background Remover',  description: 'Remove image background with AI. 100% free!',     icon: '🪄',  category: 'image',   path: '/tools/background-remover',   color: 'from-violet-500/20 to-purple-500/20', accent: 'text-violet-400',  border: 'hover:border-violet-500/50',  popular: true },
  // Text Tools
  { id: 'word-counter',         name: 'Word Counter',        description: 'Count words, characters, sentences and more',      icon: '🔢',  category: 'text',    path: '/tools/word-counter',         color: 'from-violet-500/20 to-purple-500/20', accent: 'text-violet-400',  border: 'hover:border-violet-500/50' },
  { id: 'case-converter',       name: 'Case Converter',      description: 'Convert text to UPPER, camelCase, snake_case',     icon: 'Aa',  category: 'text',    path: '/tools/case-converter',       color: 'from-fuchsia-500/20 to-pink-500/20',  accent: 'text-fuchsia-400', border: 'hover:border-fuchsia-500/50' },
  // Dev Tools
  { id: 'json-formatter',       name: 'JSON Formatter',      description: 'Format, validate and minify JSON instantly',       icon: '{ }', category: 'dev',     path: '/tools/json-formatter',       color: 'from-emerald-500/20 to-green-500/20', accent: 'text-emerald-400', border: 'hover:border-emerald-500/50', popular: true },
  // Utility
  { id: 'qr-code-generator',    name: 'QR Code Generator',   description: 'Generate QR codes for URLs, WiFi, UPI and more',  icon: '📱',  category: 'utility', path: '/tools/qr-code-generator',    color: 'from-indigo-500/20 to-violet-500/20', accent: 'text-indigo-400',  border: 'hover:border-indigo-500/50',  popular: true },
  { id: 'resume-ats-checker',   name: 'Resume ATS Checker',  description: 'Check if your resume passes ATS filters. Free!',  icon: '📋',  category: 'utility', path: '/tools/resume-ats-checker',   color: 'from-amber-500/20 to-yellow-500/20',  accent: 'text-amber-400',   border: 'hover:border-amber-500/50',   popular: true },
  { id: 'password-generator',   name: 'Password Generator',  description: 'Generate strong, secure passwords instantly',      icon: '🔐',  category: 'utility', path: '/tools/password-generator',   color: 'from-rose-500/20 to-red-500/20',      accent: 'text-rose-400',    border: 'hover:border-rose-500/50' },
  { id: 'uuid-generator',       name: 'UUID Generator',      description: 'Generate unique UUIDs for your projects',          icon: '🆔',  category: 'utility', path: '/tools/uuid-generator',       color: 'from-sky-500/20 to-blue-500/20',      accent: 'text-sky-400',     border: 'hover:border-sky-500/50' },
]

export const CATEGORIES = [
  { id: 'all',     label: 'All Tools',    icon: '⚡' },
  { id: 'pdf',     label: 'PDF Tools',    icon: '📄' },
  { id: 'image',   label: 'Image Tools',  icon: '🖼️' },
  { id: 'text',    label: 'Text Tools',   icon: '✍️' },
  { id: 'dev',     label: 'Dev Tools',    icon: '💻' },
  { id: 'utility', label: 'Utility',      icon: '🔧' },
]